{
    'name': 'Milk Distribution Management',
    'version': '3.0',
    'summary': 'Complete Milk Distributor ERP',
    'author': 'Karan',
    'depends': ['base', 'account', 'product', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/cron.xml',
        'views/dispatch_views.xml',
        'views/ledger_views.xml',
        'views/cash_views.xml',
        'views/daily_summary_views.xml',
        'views/dealer_rate_views.xml',
        'views/outstanding_report_views.xml',
        'views/dealer_statement_views.xml',
        'views/product_sales_views.xml',
        'views/driver_performance_views.xml',
        'views/monthly_closing_views.xml',
        'views/menu.xml',
        'reports/bill_report.xml',
        'reports/driver_sheet.xml',
        'reports/outstanding_report.xml',
        'reports/dealer_statement.xml',
        'reports/payment_receipt.xml',
        'reports/product_sales_report.xml',
        'reports/monthly_closing_report.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
