import logging
from odoo import models, fields, api
from odoo.exceptions import UserError, ValidationError

_logger = logging.getLogger(__name__)


class MilkCrateBilling(models.Model):
    """
    Crate rental charge bill for a dealer over a date range.

    Generated by MilkCrateBillingWizard from milk.crate.ledger data.
    Stays in draft until a manager approves it, at which point:
      1. An out_invoice is posted for the total rental charge.
      2. The partner ledger is updated on date_to.
    """
    _name = 'milk.crate.billing'
    _description = 'Crate Billing'
    _order = 'date_to desc, partner_id'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _rec_name = 'name'

    name = fields.Char(
        string='Reference', default='New', readonly=True, copy=False,
        tracking=True,
    )
    partner_id = fields.Many2one(
        'res.partner', string='Dealer', required=True,
        index=True, tracking=True,
    )
    date_from = fields.Date(string='From Date', required=True, tracking=True)
    date_to = fields.Date(string='To Date', required=True, tracking=True)
    charge_per_day = fields.Float(
        string='Charge / Crate / Day (Rs)', digits=(16, 2),
        help='Rate used when this billing was generated.',
    )
    line_ids = fields.One2many(
        'milk.crate.billing.line', 'billing_id', string='Daily Lines',
    )
    total_charge = fields.Float(
        compute='_compute_total', string='Total Charge (Rs)',
        digits=(16, 2), store=True,
    )
    state = fields.Selection([
        ('draft', 'Draft'),
        ('approved', 'Approved'),
    ], default='draft', string='Status', tracking=True)
    invoice_id = fields.Many2one(
        'account.move', string='Invoice', readonly=True, copy=False,
    )

    @api.depends('line_ids.charge_amount')
    def _compute_total(self):
        for rec in self:
            rec.total_charge = sum(rec.line_ids.mapped('charge_amount'))

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if vals.get('name', 'New') == 'New':
                vals['name'] = (
                        self.env['ir.sequence'].next_by_code('milk.crate.billing')
                        or 'New'
                )
        return super().create(vals_list)

    # ── Approval ─────────────────────────────────────────────────────────────

    def action_approve(self):
        """Manager-only: post invoice and update partner ledger."""
        if not self.env.user.has_group(
                'milk_distribution_management.group_milk_manager'
        ):
            raise UserError(
                "Only Milk ERP Managers can approve crate billing records."
            )
        for rec in self:
            if rec.state == 'approved':
                raise UserError(f"'{rec.name}' is already approved.")
            if not rec.line_ids:
                raise UserError("No billing lines found. Cannot approve.")
            if rec.total_charge <= 0:
                raise UserError(
                    "Total charge is zero. Nothing to invoice. "
                    "Check that the crate ledger has positive closing balances."
                )
            invoice = rec._create_invoice()
            rec._update_ledger()
            rec.write({'state': 'approved', 'invoice_id': invoice.id})
            _logger.info(
                "Crate billing %s approved — dealer: %s  charge: %.2f",
                rec.name, rec.partner_id.name, rec.total_charge,
            )

    # ── Internal helpers ─────────────────────────────────────────────────────

    def _create_invoice(self):
        self.ensure_one()
        # Use first available income account for the company
        account = self.env['account.account'].search([
            ('account_type', 'in', ['income', 'income_other']),
            ('company_id', '=', self.env.company.id),
            ('deprecated', '=', False),
        ], limit=1)
        line_vals = {
            'name': (
                f"Crate Rental — {self.date_from.strftime('%d-%m-%Y')} "
                f"to {self.date_to.strftime('%d-%m-%Y')}"
            ),
            'quantity': 1.0,
            'price_unit': self.total_charge,
        }
        if account:
            line_vals['account_id'] = account.id
        move = self.env['account.move'].sudo().create({
            'move_type': 'out_invoice',
            'partner_id': self.partner_id.id,
            'invoice_date': self.date_to,
            'invoice_date_due': self.date_to,
            'ref': self.name,
            'invoice_line_ids': [(0, 0, line_vals)],
        })
        move.action_post()
        return move

    def _update_ledger(self):
        """Add total crate charge to the partner ledger on date_to."""
        self.ensure_one()
        ledger = self.env['milk.partner.ledger'].search([
            ('partner_id', '=', self.partner_id.id),
            ('date', '=', self.date_to),
        ], limit=1)
        if ledger:
            ledger.sudo().write({
                'today_bill': ledger.today_bill + self.total_charge,
            })
        else:
            last = self.env['milk.partner.ledger'].search([
                ('partner_id', '=', self.partner_id.id),
                ('date', '<', self.date_to),
            ], order='date desc', limit=1)
            opening = last.closing_balance if last else 0.0
            self.env['milk.partner.ledger'].sudo().create({
                'partner_id': self.partner_id.id,
                'date': self.date_to,
                'opening_balance': opening,
                'today_bill': self.total_charge,
                'received_amount': 0.0,
            })


class MilkCrateBillingLine(models.Model):
    """One line per day showing crates held and the rental charge for that day."""
    _name = 'milk.crate.billing.line'
    _description = 'Crate Billing Line'
    _order = 'date'

    billing_id = fields.Many2one(
        'milk.crate.billing', ondelete='cascade', required=True,
    )
    date = fields.Date(string='Date', required=True)
    closing_crates = fields.Integer(
        string='Crates Held', readonly=True,
        help='Closing crate balance with the dealer on this date.',
    )
    charge_per_day = fields.Float(
        string='Rate (Rs/Crate/Day)', digits=(16, 2), readonly=True,
    )
    charge_amount = fields.Float(
        compute='_compute_amount', string='Charge (Rs)',
        digits=(16, 2), store=True,
    )

    @api.depends('closing_crates', 'charge_per_day')
    def _compute_amount(self):
        for rec in self:
            rec.charge_amount = rec.closing_crates * rec.charge_per_day


class MilkCrateBillingWizard(models.TransientModel):
    """
    Generates crate billing records for a date range.

    Reads milk.crate.ledger for each dealer's daily closing balance,
    multiplies by that dealer's crate_charge_per_day, and creates
    milk.crate.billing records in draft state for manager review.

    Pre-requisite: run Crates → Generate Crate Ledger for the same range first.
    """
    _name = 'milk.crate.billing.wizard'
    _description = 'Generate Crate Billing'

    date_from = fields.Date(
        string='From Date', required=True, default=fields.Date.today,
    )
    date_to = fields.Date(
        string='To Date', required=True, default=fields.Date.today,
    )

    @api.constrains('date_from', 'date_to')
    def _check_dates(self):
        for rec in self:
            if rec.date_from > rec.date_to:
                raise ValidationError("'From Date' must be on or before 'To Date'.")

    def action_generate(self):
        self.ensure_one()
        Ledger = self.env['milk.crate.ledger']
        Billing = self.env['milk.crate.billing']

        # Rows with a positive closing balance in the date range
        ledger_rows = Ledger.search([
            ('date', '>=', self.date_from),
            ('date', '<=', self.date_to),
            ('closing', '>', 0),
        ])

        if not ledger_rows:
            raise UserError(
                "No crate ledger entries with a positive closing balance "
                "were found in the selected date range.\n\n"
                "Run Crates → Generate Crate Ledger for this range first."
            )

        # Group by partner; skip dealers with no charge configured
        partner_data = {}
        for row in ledger_rows:
            charge = row.partner_id.crate_charge_per_day
            if charge <= 0:
                continue
            if row.partner_id.id not in partner_data:
                partner_data[row.partner_id.id] = {
                    'partner': row.partner_id,
                    'charge_per_day': charge,
                    'lines': [],
                }
            partner_data[row.partner_id.id]['lines'].append({
                'date': row.date,
                'closing_crates': row.closing,
                'charge_per_day': charge,
            })

        if not partner_data:
            raise UserError(
                "No dealers have a 'Crate Charge per Day' rate configured.\n\n"
                "Set the rate on each dealer's contact form "
                "(Crate Charge / Day field) before generating billing."
            )

        created = self.env['milk.crate.billing']
        for data in partner_data.values():
            billing = Billing.create({
                'partner_id': data['partner'].id,
                'date_from': self.date_from,
                'date_to': self.date_to,
                'charge_per_day': data['charge_per_day'],
                'line_ids': [(0, 0, line) for line in data['lines']],
            })
            created |= billing

        return {
            'type': 'ir.actions.act_window',
            'name': 'Crate Billing',
            'res_model': 'milk.crate.billing',
            'view_mode': 'list,form',
            'domain': [('id', 'in', created.ids)],
            'target': 'current',
        }
